/** Vai trò tài khoản toàn hệ thống. Chủ trì *dự án* dùng `PROJECT_ROLES` + `Project.leader_id`, không dùng system_role `leader`. */
const SYSTEM_ROLES = {
  ADMIN: 'admin',
  VIEN_TRUONG: 'vien_truong',
  TRUONG_LAB: 'truong_lab',
  MEMBER: 'member',
  /** Người dùng thường (quyền cơ bản) — trước đây là `guest` */
  USER: 'user',
};

const SYSTEM_ROLE_VALUES = Object.values(SYSTEM_ROLES);

const USER_STATUS = {
  PENDING: 'pending',
  ACTIVE: 'active',
  REJECTED: 'rejected',
  LOCKED: 'locked',
};

const USER_STATUS_VALUES = Object.values(USER_STATUS);

const APPROVAL_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};

const APPROVAL_STATUS_VALUES = Object.values(APPROVAL_STATUS);

const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  APPROVAL_CREATED: 'APPROVAL_CREATED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_STATUS_CHANGED: 'PROJECT_STATUS_CHANGED',
  PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
  PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  MILESTONE_CREATED: 'MILESTONE_CREATED',
  MILESTONE_UPDATED: 'MILESTONE_UPDATED',
  RESEARCH_CREATED: 'RESEARCH_CREATED',
  RESEARCH_APPROVED: 'RESEARCH_APPROVED',
  RESEARCH_REJECTED: 'RESEARCH_REJECTED',
  RESEARCH_WITHDRAWN: 'RESEARCH_WITHDRAWN',
  RESEARCH_DOWNLOADED: 'RESEARCH_DOWNLOADED',
  CURRICULUM_CREATED: 'CURRICULUM_CREATED',
  CURRICULUM_APPROVED: 'CURRICULUM_APPROVED',
  CURRICULUM_REJECTED: 'CURRICULUM_REJECTED',
  CURRICULUM_WITHDRAWN: 'CURRICULUM_WITHDRAWN',
  CURRICULUM_DOWNLOADED: 'CURRICULUM_DOWNLOADED',
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  DOCUMENT_WITHDRAWN: 'DOCUMENT_WITHDRAWN',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  USER_AUTO_BANNED: 'USER_AUTO_BANNED',
  RESEARCH_PUBLIC_IP_BLOCKED: 'RESEARCH_PUBLIC_IP_BLOCKED',
  /** Viện trưởng đổi system_role (member ↔ trưởng lab) */
  SYSTEM_ROLE_CHANGED: 'SYSTEM_ROLE_CHANGED',
};

const PROJECT_STATUS = {
  PLANNING: 'planning',
  ACTIVE: 'active',
  PAUSED: 'paused',
  DONE: 'done',
  ARCHIVED: 'archived',
};

const PROJECT_STATUS_VALUES = Object.values(PROJECT_STATUS);

const PROJECT_TAGS = {
  AI_ML: 'AI/ML',
  FPGA: 'FPGA',
  ROBOTICS: 'Robotics',
  EMBEDDED: 'Embedded',
  DSP: 'DSP',
  IOT: 'IoT',
  OTHER: 'Other',
};

const PROJECT_TAG_VALUES = Object.values(PROJECT_TAGS);

const PROJECT_ROLES = {
  LEADER: 'leader',
  MEMBER: 'member',
};

const PROJECT_ROLE_VALUES = Object.values(PROJECT_ROLES);

const TASK_STATUS = {
  TODO: 'todo',
  IN_PROGRESS: 'in_progress',
  REVIEW: 'review',
  DONE: 'done',
};

const TASK_STATUS_VALUES = Object.values(TASK_STATUS);

const TASK_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
};

const TASK_PRIORITY_VALUES = Object.values(TASK_PRIORITY);

const REPORT_STATUS = {
  SUBMITTED: 'submitted',
  LATE: 'late',
  MISSING: 'missing',
};

const REPORT_STATUS_VALUES = Object.values(REPORT_STATUS);

const GIT_PROVIDERS = {
  GITHUB: 'github',
  GITLAB: 'gitlab',
  BITBUCKET: 'bitbucket',
};

const GIT_PROVIDER_VALUES = Object.values(GIT_PROVIDERS);

const GIT_VISIBILITY = {
  PRIVATE: 'private',
  PUBLIC: 'public',
  INTERNAL: 'internal',
};

const GIT_VISIBILITY_VALUES = Object.values(GIT_VISIBILITY);

// Valid project status transitions
const PROJECT_STATUS_TRANSITIONS = {
  [PROJECT_STATUS.PLANNING]: [PROJECT_STATUS.ACTIVE],
  [PROJECT_STATUS.ACTIVE]: [PROJECT_STATUS.PAUSED, PROJECT_STATUS.DONE],
  [PROJECT_STATUS.PAUSED]: [PROJECT_STATUS.ACTIVE],
  [PROJECT_STATUS.DONE]: [PROJECT_STATUS.ARCHIVED],
  [PROJECT_STATUS.ARCHIVED]: [],
};

const PROJECT_LIMITS = {
  MAX_MEMBERS: 5,
  /** Tối đa số dự án (planning / active / paused) mà một member tham gia cùng lúc */
  MAX_ACTIVE_PROJECTS_PER_USER: 2,
};

/** Hồ sơ ứng viên nhà khoa học / hợp đồng cộng tác */
const SCIENTIST_APPLICATION_STATUS = {
  PENDING_LAB_REVIEW: 'pending_lab_review',
  LAB_REJECTED: 'lab_rejected',
  PENDING_DIRECTOR_REVIEW: 'pending_director_review',
  DIRECTOR_REJECTED: 'director_rejected',
  APPROVED: 'approved',
};

const SCIENTIST_APPLICATION_STATUS_VALUES = Object.values(SCIENTIST_APPLICATION_STATUS);

/** Tài liệu kỹ thuật (Books / Documents hub) */
const DOCUMENT_STATUS = {
  DRAFT: 'draft',
  PENDING: 'pending',
  REVISION: 'revision',
  PUBLISHED: 'published',
  ARCHIVED: 'archived',
  REJECTED: 'rejected',
};

const DOCUMENT_STATUS_VALUES = Object.values(DOCUMENT_STATUS);

/** Bài công bố (Research hub) */
const RESEARCH_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};

const RESEARCH_STATUS_VALUES = Object.values(RESEARCH_STATUS);

/** Giáo trình (Curriculum hub) — workflow tại curriculum.service.js */
const CURRICULUM_STATUS = {
  DRAFT: 'draft',
  PENDING: 'pending',
  REVISION: 'revision',
  APPROVED: 'approved',
  ARCHIVED: 'archived',
  REJECTED: 'rejected',
};

const CURRICULUM_STATUS_VALUES = Object.values(CURRICULUM_STATUS);

const COMMITMENT_MODEL_TYPE = {
  MODEL_1: 'MODEL_1',
  MODEL_2: 'MODEL_2',
  MODEL_3: 'MODEL_3',
};

const COMMITMENT_MODEL_TYPE_VALUES = Object.values(COMMITMENT_MODEL_TYPE);

const COMMITMENT_STATUS = {
  A_APPROVED: 'a_approved',
  PENDING_B_APPROVAL: 'pending_b_approval',
  B_APPROVED: 'b_approved',
  B_REJECTED: 'b_rejected',
  ACTIVE: 'active',
  TERMINATED: 'terminated',
};

const COMMITMENT_STATUS_VALUES = Object.values(COMMITMENT_STATUS);

module.exports = {
  SYSTEM_ROLES,
  SYSTEM_ROLE_VALUES,
  USER_STATUS,
  USER_STATUS_VALUES,
  APPROVAL_STATUS,
  APPROVAL_STATUS_VALUES,
  AUDIT_ACTIONS,
  PROJECT_STATUS,
  PROJECT_STATUS_VALUES,
  PROJECT_TAGS,
  PROJECT_TAG_VALUES,
  PROJECT_ROLES,
  PROJECT_ROLE_VALUES,
  TASK_STATUS,
  TASK_STATUS_VALUES,
  TASK_PRIORITY,
  TASK_PRIORITY_VALUES,
  REPORT_STATUS,
  REPORT_STATUS_VALUES,
  GIT_PROVIDERS,
  GIT_PROVIDER_VALUES,
  GIT_VISIBILITY,
  GIT_VISIBILITY_VALUES,
  PROJECT_STATUS_TRANSITIONS,
  PROJECT_LIMITS,
  SCIENTIST_APPLICATION_STATUS,
  SCIENTIST_APPLICATION_STATUS_VALUES,
  DOCUMENT_STATUS,
  DOCUMENT_STATUS_VALUES,
  RESEARCH_STATUS,
  RESEARCH_STATUS_VALUES,
  CURRICULUM_STATUS,
  CURRICULUM_STATUS_VALUES,
  COMMITMENT_MODEL_TYPE,
  COMMITMENT_MODEL_TYPE_VALUES,
  COMMITMENT_STATUS,
  COMMITMENT_STATUS_VALUES,
};